version: '3.7'

services:
  mongodb:
    image: mongo:4.0.3-xenial
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: ["mongod", "--smallfiles"]
